### ISSUE TITLE
Crashes when saving results from an AWS service with 2 'names'

### ISSUE THREAD

**Issue by avs3323** [garnaat/placebo#10]
The following code causes placebo to crash:

iot_data = session.client(client='iot-data')
.....
iot_data.meta.placebo.save('iot-data')

On line 49 in placebo.py:

_, service_name, operation_name = kwargs['event_name'].split('.')

Where kwargs['event_name'] is "after-call.data.iot.GetThingShadow"

**Comment by garnaat** [comment]
Thanks for the report.  Could you possibly paste in the whole stack trace?

**Comment by avs3323** [comment]
Oops, I was mistaken, it actually happens when you make a service call.  Here is the stack trace

iot.get_thing_shadow(thingName="XXXXXXX")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 391, in _make_api_call
    model=operation_model
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/placebo.py", line 54, in _record_data
    _, service_name, operation_name = kwargs['event_name'].split('.')
ValueError: too many values to unpack

**Comment by garnaat** [comment]
Hmm, it looks like the event is being constructed in a way that I was not anticipating.  I'll have to make that code smarter about breaking up the event.  I'll try to get a fix in today.

**Comment by garnaat** [comment]
Actually, it was easier than I thought.  I think this should fix it.  I'm not using the ``iot-data`` service so can't confirm.  Please re-open if you still have problems.

**Comment by avs3323** [comment]
Hi,

Thanks for making this fix!

I ran into another issue, one of the API calls returns a botocore.streamingBody, which causes an issue on JSON serialization:

>>>>> python iot_test.py 
{'data.iot.GetThingShadow': {'index': 0, 'responses': [(200, {u'payload': <botocore.response.StreamingBody object at 0x109db4a10>, 'ResponseMetadata': {'HTTPStatusCode': 200, 'RequestId': '73d3ede2-cd17-4bf7-afe5-0facc8f194a1'}})]}}
Traceback (most recent call last):
  File "iot_test.py", line 8, in <module>
    iot.meta.placebo.save('my_saved_iot_calls.json')
  File "/usr/local/lib/python2.7/site-packages/placebo.py", line 68, in save
    json.dump(self.mock_responses, fp, indent=4, default=serialize)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python2.7/site-packages/placebo.py", line 164, in serialize
    raise TypeError("Type not serializable")
TypeError: Type not serializable

**Comment by garnaat** [comment]
I have created a new issue to track this
#12
