### ISSUE TITLE
JSON serialization error

### ISSUE THREAD

**Issue by garnaat** [garnaat/placebo#12]
I ran into another issue, one of the API calls returns a botocore.streamingBody, which causes an issue on JSON serialization:

```
>>>>> python iot_test.py 
{'data.iot.GetThingShadow': {'index': 0, 'responses': [(200, {u'payload': <botocore.response.StreamingBody object at 0x109db4a10>, 'ResponseMetadata': {'HTTPStatusCode': 200, 'RequestId': '73d3ede2-cd17-4bf7-afe5-0facc8f194a1'}})]}}
Traceback (most recent call last):
  File "iot_test.py", line 8, in <module>
    iot.meta.placebo.save('my_saved_iot_calls.json')
  File "/usr/local/lib/python2.7/site-packages/placebo.py", line 68, in save
    json.dump(self.mock_responses, fp, indent=4, default=serialize)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python2.7/site-packages/placebo.py", line 164, in serialize
    raise TypeError("Type not serializable")
TypeError: Type not serializable
```

**Comment by gffhcks** [comment]
This is the same type of issue as #5 and can probably be handled (roughly) the same way - serialize it as a dictionary containing the module, class, and the init() arguments required to create the object. It's a bit more tricky than datetime objects, though, because it's dealing with content validation and socket timeouts. It would be nice to be able to simulate bad responses and raise an exception when the content is cut off, for example, but I'm not sure how that could be implemented.

**Comment by avs3323** [comment]
Yes, I wrote a quick workaround that kind of does this.

On the serialize, I call read() on the StreamingBody, and store that as a string.

On deserialize, I stick that string into a io.StringIO object, so that consumers can still call read() on it and get a result.

It doesn't allow testing of anything StreamingBody related, but that is ok with me

**Comment by zdot** [comment]
+1 on this issue. Would be great to have a way to handle StreamingBody. Thank you for a great library.

**Comment by garnaat** [comment]
The above commit adds the very simple support described by @avs3323 above which really does everything I need it to do at the moment.

**Comment by zdot** [comment]
Thanks for the reply. I will look into using the functionality in this commit.
