### ISSUE TITLE
AttributeError: 'FakeHttpResponse' object has no attribute 'content'

### ISSUE THREAD

**Issue by joshuaroot** [garnaat/placebo#56]
```
Traceback (most recent call last):
  File "~/c7n/policy.py", line 192, in run
    results = a.process(resources)
  File "~/c7n/resources/s3.py", line 433, in process
    Bucket=b['Name']).get('LocationConstraint', 'us-east-1')
  File "~/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "~/lib/python2.7/site-packages/botocore/client.py", line 533, in _make_api_call
    model=operation_model, context=request_context
  File "~/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "~/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "~/lib/python2.7/site-packages/botocore/handlers.py", line 434, in parse_get_bucket_location
    response_body = http_response.content
AttributeError: 'FakeHttpResponse' object has no attribute 'content'
```

**Comment by aiell0** [comment]
Bumping this, as it looks like this still has not been fixed. I am having the same issue with the s3 location API.
