### ISSUE TITLE
Using Placebo to unit test legacy code

### ISSUE THREAD

**Issue by alexharv074** [garnaat/placebo#64]
I hope it's OK to ask a question here. I can't find this explained in the docs.

I have legacy code that does a lot of stuff using the default Boto3 session, e.g.

~~~ python
import boto3
client = boto3.client('ec2')
client.describe_images(DryRun=False, ImageIds=[ami_id])
...
~~~

However, docs here at this project seem to imply that I need to manage the session explicity, i.e.

~~~ python
import boto3
session = boto3.Session()
client = session.client('ec2')
client.describe_images(DryRun=False, ImageIds=[ami_id])
...
~~~

Then you need to attach Placebo to `session`.

But is it possible to attach Placebo somehow to the default session -- or would I have to refactor all my legacy code before I could use Placebo on it?

Thanks,

**Comment by alexharv074** [comment]
Hi @garnaat , is this an easy yes/no question?

**Comment by alexharv074** [comment]
See also https://stackoverflow.com/questions/45530839/using-the-default-session-in-placebo-to-unit-test-boto3-code/45595495

**Comment by alexharv074** [comment]
@garnaat , Your suggestion in the SO post leads to a failure (as seen in my Jenkins log):

~~~ 
14:21:37 + python /var/lib/jenkins/jobs/Encrypt_AMI/workspace/scripts/aws_ec2_copy_image.py --encrypted --source-image-id ami-52293031 jenkins
14:21:38 Traceback (most recent call last):
14:21:38   File "/var/lib/jenkins/jobs/Encrypt_AMI/workspace/scripts/aws_ec2_copy_image.py", line 208, in <module>
14:21:38     main()
14:21:38   File "/var/lib/jenkins/jobs/Encrypt_AMI/workspace/scripts/aws_ec2_copy_image.py", line 186, in main
14:21:38     pill = placebo.attach(boto3.session, '/tmp')
14:21:38   File "/usr/lib/python2.6/site-packages/placebo/__init__.py", line 20, in attach
14:21:38     pill.attach(session, data_path)
14:21:38   File "/usr/lib/python2.6/site-packages/placebo/pill.py", line 130, in attach
14:21:38     session.events.register('creating-client-class', self._create_client)
14:21:38 AttributeError: 'module' object has no attribute 'events'
~~~

**Comment by alexharv074** [comment]
If you have any high-level suggestions on how to fix, I'm more than happy to do implementation and testing of the feature/change.

**Comment by alexharv074** [comment]
I figured it out
https://stackoverflow.com/questions/45530839/using-the-default-session-in-placebo-to-unit-test-boto3-code/45628669#45628669
